      SUBROUTINE EIRENE_SPTUSR
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_SPTUSR

      SUBROUTINE EIRENE_SP1USR(WMIN,FMASS,FCHAR,FLXSP,
     .             IGASP,
     .             YIELD1,
     .             ISPZP,ESPTP,VSPTP,VXSPTP,VYSPTP,VZSPTP,
     .             IGASC,
     .             YIELD2,
     .             ISPZC,ESPTC,VSPTC,VXSPTC,VYSPTC,VZSPTC,
     .             YSPTWL,QQS)
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      INTEGER :: IGASC, IGASP
      INTEGER :: ISPZC, ISPZP
      REAL(DP) :: WMIN, FMASS, FCHAR, FLXSP
      REAL(DP) :: YIELD1, YIELD2, ESPTC, VSPTC, ESPTP,
     .            VSPTP, VXSPTP, VYSPTP, VZSPTP,
     .            VXSPTC, VYSPTC, VZSPTC, QQS
      REAL(DP) :: YSPTWL !VK NUMBER OF WALL ATOMS IN SPUTTERED PARTICLE

      RETURN
      END SUBROUTINE EIRENE_SP1USR
